modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/ricksouth/serilum-mc-mods/labels/Mod:%20Husk%20Spawn"
logoFile="icon.png"

[[mods]]
modId="huskspawn"
version="3.4"
displayName="Husk Spawn"
displayURL="https://curseforge.com/minecraft/mc-mods/husk-spawn"
authors="Rick South"
description='''Adds a chance for husks to spawn naturally everywhere instead of a zombie.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Adam E, Alister, aternosorg, Cherriesaurus, FireStriker, Greg Johnson, Kreezxil, Michael W. S., Mir3JonCZ, Rebecca Hb., Shana Gitnick, silver Bowsman, Tyler Behl   

If you would like to contribute too, check out https://ricksouth.com/donate. Appreciate it! <3   
'''

[[dependencies.huskspawn]]
    modId="collective"
    mandatory=true
    versionRange="[7.12,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.huskspawn]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "huskspawn_neoforge.mixins.json"